import React from 'react'

const Dashboard = () => {
  return (
    <div className='p-5'>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias velit cumque voluptas nulla, aut quo beatae eos. Aperiam eaque praesentium dolores perferendis est dolorem quisquam provident, ipsa sit quam reprehenderit! Blanditiis eveniet consequatur sunt natus laborum officiis cumque. Asperiores tempore soluta repudiandae sint alias pariatur atque deleniti similique quaerat nisi.</p>
      <p>Nisi voluptatibus corporis reprehenderit, sequi minus atque eius nobis quidem exercitationem cupiditate nemo in cumque accusantium dolore aliquam voluptates et natus delectus nesciunt cum laborum molestiae quia officia ullam. Maxime suscipit neque quis rerum, architecto iste excepturi soluta, veniam eaque sunt velit consequuntur recusandae, voluptate laborum dolores ab! Officia, iusto?</p>
      <p>Alias, odit repudiandae ex at enim blanditiis, nam, molestias incidunt vel officiis quos soluta doloribus sequi. Qui, praesentium. Eaque, totam iure possimus unde molestiae omnis blanditiis voluptates, delectus quo assumenda et minus, ut voluptatum facilis ad. Amet accusantium exercitationem provident cupiditate veniam quia est aliquid dignissimos molestiae recusandae? Cumque, beatae.</p>
      <p>Ad reiciendis similique ut tempore, et eius ab doloremque veniam porro quod nulla. Soluta reprehenderit, distinctio nesciunt maxime reiciendis alias deserunt, ut saepe, ipsam asperiores deleniti accusamus aliquam perferendis nihil molestias. Nihil minima facilis vel quisquam esse aut tempora. Odio dolor nihil nesciunt quaerat quos non vitae alias exercitationem asperiores!</p>
      <p>Rerum optio illo quibusdam, dolorum non velit cumque laborum amet praesentium unde veritatis sed deserunt. Nisi neque eos harum! Modi, itaque ipsa dicta saepe enim cum dolorem, impedit molestiae nemo distinctio, excepturi recusandae natus temporibus consectetur ipsam eligendi. Est consectetur omnis perferendis expedita excepturi totam ipsam odio minima ab dolores.</p>
      <p>Non minima nihil consequatur velit ab quam odio est aliquam enim. Eveniet repellendus error nemo aliquam cumque rerum accusamus doloremque molestias nesciunt facere quas distinctio quia dolore repellat veniam, voluptatibus, ipsam quidem officiis harum laborum amet deleniti recusandae incidunt? Culpa nisi dicta suscipit. Tempore nam quis repellendus et, earum voluptate?</p>
      <p>Sint qui modi, debitis ut incidunt illum voluptate voluptatum veritatis magni tenetur aliquam officiis necessitatibus fugiat recusandae impedit ratione assumenda dolorum ad repellat minima commodi nobis quae id? Fuga cum unde neque reprehenderit hic quod explicabo voluptatibus, dolor suscipit mollitia nesciunt nihil praesentium ea non nisi ullam fugiat? Praesentium, reiciendis?</p>
      <p>Rem consectetur incidunt veritatis saepe aliquid iure? Nulla ea, nemo adipisci provident dolorem temporibus nihil totam incidunt explicabo facere ad illo eum magnam aliquid harum error aut quas et aperiam aliquam sunt fuga non! Vel ea totam delectus ratione! Quis saepe magnam sapiente eos rerum ullam debitis harum obcaecati necessitatibus.</p>
      <p>Voluptas aliquid tempore omnis itaque est eum! Magnam commodi libero dicta at voluptatibus nostrum officiis ullam perferendis nihil enim, cumque porro perspiciatis facilis saepe amet aliquam nobis illo? Tempore, modi dolor? Cupiditate earum assumenda eius itaque illo, enim aliquam sint nostrum, fugiat aut veritatis modi culpa reprehenderit atque natus quaerat?</p>
      <p>Eveniet architecto officiis aperiam fugit dolores molestiae explicabo minima repellat asperiores nostrum sequi labore ipsam eius voluptates optio, delectus rem distinctio quia, velit commodi sit necessitatibus excepturi? Temporibus voluptatum, molestias accusamus autem ipsam quos exercitationem dicta odio expedita ut nisi at tenetur maiores, ad, nihil soluta magni blanditiis voluptatibus? Necessitatibus.</p>
    </div>
  )
}

export default Dashboard